param(
  [string]$OutputFile = "stickers.js"
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
$imageRoot = Join-Path $projectRoot "图片"
$allowedExtensions = @(".png", ".jpg", ".jpeg", ".gif", ".webp")
$packNames = @("贝拉", "嘉然", "乃琳")
$packs = [ordered]@{}

foreach ($packName in $packNames) {
  $packRoot = Join-Path $imageRoot $packName
  if (-not (Test-Path -LiteralPath $packRoot -PathType Container)) {
    throw "Missing sticker pack directory: $packRoot"
  }

  $stickerRows = Get-ChildItem -LiteralPath $packRoot -Recurse -File |
    Where-Object { $_.Extension.ToLowerInvariant() -in $allowedExtensions } |
    ForEach-Object {
      $withinPack = $_.FullName.Substring($packRoot.Length + 1).Replace("\", "/")
      $topFolder = $withinPack.Split("/")[0]
      $folderOrder = if ($topFolder -match '^(\d+)-') { [int]$Matches[1] } else { 0 }
      [pscustomobject]@{
        FolderOrder = $folderOrder
        WithinPack = $withinPack
        ProjectPath = $_.FullName.Substring($projectRoot.Length + 1).Replace("\", "/")
      }
    }

  $packs[$packName] = @(
    $stickerRows |
      Sort-Object @{ Expression = "FolderOrder"; Descending = $true }, @{ Expression = "WithinPack"; Descending = $false } |
      ForEach-Object { $_.ProjectPath }
  )
}

$json = $packs | ConvertTo-Json -Depth 4
$content = "// Generated by tools/generate-stickers.ps1. Do not edit paths by hand.`nwindow.ASOUL_STICKER_PACKS = $json;`n"
$target = if ([System.IO.Path]::IsPathRooted($OutputFile)) { $OutputFile } else { Join-Path $projectRoot $OutputFile }
[System.IO.File]::WriteAllText($target, $content, [System.Text.UTF8Encoding]::new($false))

$total = ($packs.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum
Write-Output "Generated $target with $total sticker paths."
